apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeper.kafka
spec:
  selector:
    matchLabels:
      app: run6
  template:
    metadata:
      labels:
        app: run6
    spec:
      containers:
      - name: zookeeper
        image: confluentinc/cp-zookeeper:5.0.0
        labels:
          app: zookeeper
        ports:
          - containerPort: 2181
        command:
        - "./etc/confluent/docker/run"
        env:
          - name: ZOOKEEPER_CLIENT_PORT
            value: "2181"
          - name: ZOOKEEPER_TICK_TIME
            value: "2000"
        resources:
          limits:
            memory: "512Mi"
            cpu: "300m"
      - name: kafka
        image: confluentinc/cp-kafka:5.0.0
        ports:
          - containerPort: 9092
          - containerPort: 9094
        command:
        - "./etc/confluent/docker/run"
        env:
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: "zookeeper-service:2181"
          - name: KAFKA_ADVERTISED_LISTENERS
            value: "INSIDE://kafka:9092,OUTSIDE://localhost:9094"
          - name: KAFKA_LISTENERS 
            value: "INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9094"
          - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP 
            value: "INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT"
          - name: KAFKA_INTER_BROKER_LISTENER_NAME
            value: "INSIDE"
          - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR 
            value: "1"
          - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS 
            value: "0"
          - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE 
            value: "true"
          - name: KAFKA_NUM_PARTITIONS 
            value: "4"
        resources:
          limits:
            memory: "1024Mi"
            cpu: "700m"
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
spec:
  selector:
    app: zookeeper
  ports:
    - name: zk
      protocol: TCP
      port: 2181
      targetPort: 2181