load_run_1:
	python3 -c "import loader; loader.load_1M_ignore_all_except_first_and_last()"

load_run_2:
	python3 -c "import loader; loader.load_1M_include_all()"

clean:
	python3 -c "import loader; loader.clear_topic()"
